# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Pet Smile' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!
  pod 'SQLite.swift', '~> 0.12.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'CSV.swift', '~> 2.4.2'
  # Pods for Clima

end
